# Generated by Django 4.2 on 2025-09-25 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='日记内容')),
                ('weather', models.SmallIntegerField(choices=[('1', '☀️ 晴天'), ('2', '☁️ 多云'), ('3', '🌧️ 雨天'), ('4', '❄️ 雪天'), ('5', '💨 大风'), ('6', '🌫️ 雾天'), ('7', '⛈️ 雷雨'), ('8', '🌤️ 一般')], verbose_name='天气')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='NoteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50, verbose_name='日记本名称')),
                ('description', models.CharField(max_length=50, verbose_name='描述')),
                ('cover_color', models.SmallIntegerField(choices=[(1, '#A7CE4F'), (2, '#E7DA96'), (3, '#9EBAC6'), (4, '#F79A57'), (5, '#EB4A59'), (6, '#5E595A'), (7, '#BA55D3')], default=1, verbose_name='封面颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Web.userinfo')),
            ],
        ),
    ]
