# Generated by Django 3.2 on 2025-09-27 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diarycontents',
            name='notebook',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Web.notebook'),
            preserve_default=False,
        ),
    ]
