# Generated by Django 3.2 on 2025-09-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0003_alter_diarycontents_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diarycontents',
            name='weather',
            field=models.CharField(choices=[(1, '☀️ 晴天'), (2, '☁️ 多云'), (3, '🌧️ 雨天'), (4, '❄️ 雪天'), (5, '💨 大风'), (6, '🌫️ 雾天'), (7, '⛈️ 雷雨'), (8, '🌤️ 一般')], max_length=50, verbose_name='天气'),
        ),
    ]
